services:
  bot:
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    env_file:
      - config/.env
    environment:
      - TZ=Europe/Moscow
    extra_hosts:
      - "host.docker.internal:host-gateway"