"""Добавлен столбец в Chat для связи с таблицей Project

Revision ID: 300cabfe1bb4
Revises: 407a101db562
Create Date: 2025-03-10 12:41:26.388055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "300cabfe1bb4"
down_revision: Union[str, None] = "407a101db562"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "projects", ["uuid"])
    op.add_column("chats", sa.Column("project_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "chats", "projects", ["project_id"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="unique")
    op.drop_constraint(None, "chats", type_="foreignkey")
    op.drop_column("chats", "project_id")
    # ### end Alembic commands ###
