"""Добавить поле (удален deleted_at) в TimestampMixin

Revision ID: 407a101db562
Revises: 72d80104dc5a
Create Date: 2025-03-09 20:02:33.832736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "407a101db562"
down_revision: Union[str, None] = "72d80104dc5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chatandusers", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("projects", "deleted_at")
    op.drop_column("chatandusers", "deleted_at")
    # ### end Alembic commands ###
